Working on global init script

diff --git a/scripts/vbs_daemon b/scripts/vbs_daemon
--- a/scripts/vbs_daemon
+++ b/scripts/vbs_daemon
@@ -19,7 +19,7 @@ PPRIORITY=no
 RTPRIO=20
 TIMEOUT=5
 DEBVARS=/lib/init/vars.sh
-DISTRO=DEBIAN
+DISTRO=OTHER
 
 SCRIPTNAME=vbs_daemon
 #scriptPath=${0%${SCRIPTNAME}}
@@ -47,6 +47,7 @@ then
   DISTRO=DEBIAN
 fi
 
+#Doesnt work..
 PPSTRING=""
 if [ "$PPRIORITY" == "yes" ]
 then
@@ -65,6 +66,22 @@ fi
 
 # Function that starts the daemon/service
 #
+do_hugepages()
+{
+  echo $(date --rfc-3339=seconds) "Checking if hugepages are in use.." | tee -a  $LOGFILE
+  if [ "$(cat $CFGFILE |egrep -v "^#" |grep use_hugepage |cut -d' ' -f3)" == "1;" ] 
+  then
+    if [ "$(cat /proc/sys/vm/nr_hugepages)" == "0" ]
+    then
+      echo $(date --rfc-3339=seconds) "Initializing hugepages" | tee -a  $LOGFILE
+      init_hugepages -c
+    else
+      echo $(date --rfc-3339=seconds) "Hugepages already initialized" | tee -a  $LOGFILE
+    fi
+  else
+    echo "Hugepages not in use"
+  fi
+}
 do_start()
 {
   # Return
@@ -75,25 +92,26 @@ do_start()
     echo "vlbistreamer already running"
     return 1;
   else
+    do_hugepages
     #sudo -u $USER $BINDIR/vlbistreamer &>> $LOGFILE &
     #if [ -n "$(ps -A -o cmd | grep -v grep|grep -i $BINDIR/vlbistreamer)" ] ; then
-    echo $(date --rfc-3339=seconds) "Checking if hugepages are in use.." | tee -a  $LOGFILE
-    if [ "$(cat $CFGFILE |egrep -v "^#" |grep use_hugepage |cut -d' ' -f3)" == "1;" ] 
+    retval=-1
+    if [ "$DISTRO" == "DEBIAN" ]
     then
-      if [ "$(cat /proc/sys/vm/nr_hugepages)" == "0" ]
-      then
-	echo $(date --rfc-3339=seconds) "Initializing hugepages" | tee -a  $LOGFILE
-	init_hugepages -c
-      fi
+      start-stop-daemon --start --make-pidfile --pidfile $PIDFILE -c ${USER}:{GROUP} --user ${USER} --group ${GROUP} --background --name $NAME ${PPSTRING} --quiet  --exec $DAEMON -- $DAEMON_ARGS
+      retval=$?
     else
-      echo "Hugepages not in use"
+      #TODO: -g ${group} doesn't work for some reason
+      sudo -u ${USER} $DAEMON &
+      retval=$?
+      echo $! > $PIDFILE
     fi
-    if start-stop-daemon --start --make-pidfile --pidfile $PIDFILE -c ${USER}:{GROUP} --user ${USER} --group ${GROUP} --background --name $NAME ${PPSTRING} --quiet  --exec $DAEMON -- $DAEMON_ARGS ; then
+    if [ "$retval" == 0 ]
+    then
       if [ "$PPRIORITY" == "yes" ]
       then
 	#TODO: This is not the correct way
 	sleep 1
-	#chrt -f -p $RTPRIO  $(ps -A |grep -i vlbistreamer |cut -d ' ' -f2)
 	chrt -f -p $RTPRIO  $(cat $PIDFILE)
       fi
       #TODO: whats the right way to check if it started ok? 
@@ -149,60 +167,66 @@ do_reload() {
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    if [ "$DISTRO" == "DEBIAN" ]
+    then
+      [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+      do_start
+      case "$?" in
+	0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+  else
+    echo "Not in debian so daemon start not logged"
+    do_start
+  fi
+  ;;
+stop)
+  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+  2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+esac
+;;
+  status)
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
+  #reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
+  restart|force-reload)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+	  0) log_end_msg 0 ;;
+	1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
+    ;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+    # Failed to stop
+    log_end_msg 1
+    ;;
+esac
+;;
+  *)
+    #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
 :
